spring:
  application:
    name: forum-admin
  profiles:
    active: prod
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

JWTParam:
  BASE64_ENCODE_SECRET_KEY: "FiHs5Ib3jVZlOk3TKDiSho=="
  BEARER: "jgxq"
  JG_COOKIE: "admin_jgxq_cookie"
  KEY_LENGTH: 8
  EXP_DAYS: 90 # JWT过期时间：多少天后失效
  EXP_TIME: "04:00:00" # JWT过期时间：具体几点（24小时制）

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)